export const UPDATE_AUTH_INPUT = 'UPDATE_AUTH_INPUT';
export const AUTH_SUCCEED = 'AUTH_SUCCEED';
export const AUTH_FAIL = 'AUTH_FAIL';
export const UPDATE_USER_TOKENS = 'UPDATE_USER_TOKENS';
export const UPDATE_ALL_TOKENS = 'UPDATE_ALL_TOKENS';
export const UPDATE_ADDED_TOKEN = 'UPDATE_ADDED_TOKEN';
